libp2p/go-libp2p-core

metrics/bandwidth.go
metrics/bandwidth_test.go
metrics/reporter.go

I'd like to expose these in go-ipfs and, eventually, the ipfs webui.

metrics: allow getting metrics by peer/protocol

---

crypto/key_test.go
go.mod
go.sum
peer/peer_serde_test.go
peer/peer_test.go
test/crypto.go
test/peer.go

Avoids circular module dependency.

absorb {crypto,peer} test utils.

---

peer/addrinfo.go

* Use SplitLast to avoid allocating too much.
* Avoid converting to/from strings when working with multiaddrs.

chore: cleanup address parsing

---

peer/addrinfo.go
peer/addrinfo_test.go

* SplitAddr is a simpler way to split an address into a multiaddr and an ID.
* AddrInfosFromP2pAddrs converts a set of multiaddrs into a set of AddrInfos.

feat(peer): implement AddrInfosFromP2pAddrs and SplitAddr

---

peerstore/peerstore.go

Necessary to apply protocol deltas from identify push (#17).

peerstore/protobook: support removing protocols.

---

event/identify.go

This PR adds new events to be emitted on initial peer identification.

add events for identify

---

crypto/ecdsa.go
crypto/ed25519.go
crypto/key.go

Removes reliance on short-circuiting equality comparisons which can be cryptographically unsound.

Replace bytes.Equal -> subtle.ConstantTimeCompare

---

crypto/key.go
crypto/key_test.go

Stops us from panicking in the event that we receive a curve we don't support.

Return error rather than panic in GenerateEKeyPair

---

test/crypto.go
test/peer.go

This implements #4 from #43.
fixes #43

avoid duplicate randomly generated keys/peer-ids

---

event/bus.go

Could only break code depending on panic recovery. Proposed solution to https://github.com/libp2p/go-eventbus/issues/20.

Return error in Emit

---

go.mod
go.sum
peer/peer.go

This PR is a non-substantive change with the goal of making this method
`ExtractPublicKey` from a `peer.ID` clearer to the reader. This goal is
accomplished by using the full name of the identity hash code `IDENTITY` instead
of the deprecated `ID` code. This change makes its clearer to the reader that
there is a trivial way to compute the public key given the digest. Without this
change it is easy to confuse `ID` with a concept relating to peer IDs (and thus
implying this function somehow computes a hash pre-image to get the
corrresponding public key.

Compare multihash `Code` to `IDENTITY` when extracting public key

---

crypto/key.go

We were storing the key data in the cache instead of the key wrapped in the protobuf. This is inconsistent with how we return the data in the `Bytes()` function and was causing the `TestFixtures` test to fail.

fix: Store marshalled protobuf in cache for RsaPublicKey.Bytes()

---

go.mod
go.sum

There was a breaking change in the previous version that has since been reverted. Pulling in the 20190923 version is breaking our code.

Update golang.org/x/crypto to latest version

---

go.mod
go.sum
sec/insecure/insecure.go

This fixes a bug in plaintext 2.0, which according to the spec should use varints for delimiting messages. I used `go-msgio` thinking that it used varints under the hood, but it actually uses 4 byte unsigned ints instead.
This switches out msgio for gogoprotobuf's varint delimited Reader / Writer types.

use varints for delimiting plaintext 2.0 msgs

---

go.mod
go.sum
metrics/bandwidth.go

We could, alternatively, provide a "GC period" along with a Close method.
However, letting the application choose when to trim idle timers seems like a
more flexible option.

feat(metrics): add function to trim idle meters

---

crypto/key.go

The docs seem to lie about what the `ConfigEncodeKey` and `ConfigDecodeKey` methods do. Currently they seem to simply be wrappers around base 64 encoding and decoding.
The simple fix is to update the docs but is it possible to get these methods
to marshal to public or private key correctly by passing a "type" (reflect.Type or something) to them?
(First day using go, otherwise I would have taken an actual stab at this)

Fix documentation missmatch for crypto methods.

---

routing/query.go

fixes https://github.com/libp2p/go-libp2p-routing/issues/41

docs(routing/query): document public query event interfaces

---

sec/insecure/insecure.go

Instead of calculated from the public key. Otherwise,
```go
remoteID.MatchesPublicKey(remotePubkey)
```
is always `True`.

fix: get `remoteID` from pb message in plaintext

---

event/addrs.go

Small update to #73 that changes the `EvtLocalPeerRecordUpdated` event struct so that it embeds a `PeerRecord` value, instead of a pointer to a `PeerRecord`. This prevents record from being modified by receivers.

Use `PeerRecord` value instead of pointer  in `EvtLocalPeerRecordUpdated`

---

LICENSE

Adding URLs to the licenses will cause go to detect this project as Apache 2.0.
fix #114

chore(license): fix license detection

---

connmgr/connmgr.go
peer/addrinfo.go
peer/peer.go
peer/peer_serde.go
peer/record.go
peer/set.go
peerstore/peerstore.go

After going through part of the code {connmgr, peer, peerstore}, I found a few inconsistencies on comment sentences.
Some comment sentences did not start with the name of the thing being described, and others did not end in a period, which causes inconsistent docs with the majority of libp2p docs and broader go ecosystem. [golang/go/wiki/CodeReviewComments#comment-sentences](https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences) recommends that we do this, which we mostly do in the codebase.
Also fixed a minor typo.

docs: uniform comment sentences

---

pnet/codec.go
pnet/codec_test.go
pnet/protector.go

Tracking issue: https://github.com/libp2p/go-libp2p/issues/795.

remove the Protector interface, introduce a PSK type

---

go.mod
go.sum
sec/insecure/insecure.go

gogo's varint reader buffers internally. If you use it then throw it away, you'll drop data. This commit reverts to using msgio, but uses the varint reader/writers instead.
We need tests. But ideally, we'd be running the transport suite tests against our transports in go-libp2p itself: https://github.com/libp2p/go-libp2p/issues/868

fix: don't drop bytes in the insecure transport

---

routing/routing.go

Count == 0 now means that we search for an unbounded number of providers.

doc(routing): document count

---

peer/record.go

This lets external protobuf structures import the PeerRecord message type and the Go code using it effectively convert between peer.PeerRecord and its protobuf implementation.

PeerRecord: Add ToProtobuf() to get a PeerRecord's equivalent protobuf struct

---

routing/query.go

This can save us some work if the caller doesn't actually care about these events.

feat: add a function to tell if a context subscribes to query events

---

peerstore/peerstore.go

Motivation: https://github.com/libp2p/go-libp2p-kad-dht/issues/594.
In a lot of cases, we simply want to know if a peer supports any one protocol among a  set of protocols.
In such cases, we currently end up doing:
```
if s, err := as.host.Peerstore().SupportsProtocols(peer, protos...); 
len(s) == 0 && err == nil {...}
```
However, this causes needless allocations as `SupportsProtocols` makes an allocation for each protocol that is supported even if we don't actually need that information.
This PR adds a `SupportsAnyProtocol ` API that allows clients to determine if the peer supports ANY of the given protocols without knowing which of the given protocols it actually supports.

Interface to verify if a peer supports a protocol without making allocations

---

network/network.go

implement Stringer for network.{Direction,Connectedness,Reachability}.

---

connmgr/decay.go

This PR introduces two features to decaying tags:
* Explicitly remove a decaying tag from a peer.
* Kill/close a decaying tag, dropping its tracking and erasing it from all peers.
---
Implementation: https://github.com/libp2p/go-libp2p-connmgr/pull/72.

decaying tags: support removal and closure.

---

connmgr/manager.go
connmgr/null.go

So that we can query whether a peer is protected; especially useful for tests.

Connection Manager: add IsProtected interface

---

alias.go

There was a typo in doc for `ProtocolID` alias

Fix typo in docs

---

sec/insecure/insecure.go

`SecureInbound` secures an inbound and not an outbound connection.

sec/insecure/insecure.go: Fix typo in doc

---

mux/mux.go
network/conn.go

Fixes #86, using option 1.
Associated PRs (These PRs will all need to be rebased after we've merged this PR and cut a new release):
- https://github.com/libp2p/go-libp2p-swarm/pull/232
- https://github.com/libp2p/go-libp2p/pull/1033
- https://github.com/libp2p/go-libp2p-kad-dht/pull/701
- https://github.com/libp2p/go-libp2p-transport-upgrader/pull/70
- https://github.com/libp2p/go-libp2p-testing/pull/31
- https://github.com/libp2p/go-ws-transport/pull/98
- https://github.com/libp2p/go-libp2p-quic-transport/pull/189
- https://github.com/libp2p/go-libp2p-yamux/pull/29
- https://github.com/libp2p/go-libp2p-mplex/pull/21
- https://github.com/libp2p/go-libp2p-webrtc-direct/pull/35

add a context to OpenStream and NewStream

---

network/context.go

For https://github.com/libp2p/go-libp2p/issues/1039.

Context to force a direct dial in the Swarm even if we have a Relayed connection

---

peer/addrinfo_serde.go
peer/addrinfo_test.go

This saves us a bunch of error prone manual decode/encode logic.

refactor: use a helper type to decode AddrInfo from JSON

---

network/conn.go
network/context.go
network/errors.go
network/network.go

It adds a transient mark in the metadata and a context option to opt-in for opening streams on transient connections.

add support for transient connections

---

event/nattype.go
network/nattype.go

For https://github.com/libp2p/go-libp2p/issues/1039.
Emit event to inform user of the NAT Device Type wrt BAT traversal i.e. Easy NAT(supports consistent endpoint translation) or Hard NAT(does NOT support consistent endpoint translation).

Event for user's NAT Device Type: Tell user if the node is behind an Easy or Hard NAT

---

transport/transport.go

doc: document Close on Transport

---

crypto/bench_test.go

fix benchmark of key verifications

---

transport/transport.go

reduce default timeouts to 15s

---

metrics/bandwidth_test.go

These tests regularly failed to stay within the 1% of the expected threshold. These tests are taken after 2.1 seconds on the wall, but before the wait-group has finished, but I think on many systems the timers are not accurate to be used reliabily within tight 
On my system (kernel configured with CONFIG_HZ=300) each tick may be inaccurate by more than 3ms, over 40 iterations the error might be as high as 1.6% for each goroutine
I chose to delete these tests because figuring out the right error threashold seems a little too magical to me, but if there's a good reason to keep these tests I can change htis PR to just increase the error threshold.

remove flaky tests

---

README.md

It's incorrect, and I'm sure we'll forget updating it every half a year. Better to say nothing.

remove minimum Go version from README

---

peer/record.go
peer/record_test.go

On Linux, this is almost always the case. Windows, however, doesn't have nanosecond accuracy.
We make the timestamp sequence numbers strictly increasing by returning the last timestamp + 1 where necessary.

fix: make timestamps strictly increasing

---

peer/addrinfo.go
peerstore/helpers.go

Specifically, move them _here_ from the peerstore. That way packages (like the DHT) that currently directly rely on the peerstore, can just use go-libp2p-core.
Moved from https://github.com/libp2p/go-libp2p-peerstore/blob/f7f22569f7d49635953638ffb11915dd3d054cf5/peerstore.go#L79-L93
With some small modifications.

feat: add helper functions for working with addr infos

---

peer/addrinfo.go
peer/addrinfo_test.go
peer/peer.go
peer/peer_serde.go
peer/peer_test.go

These functions have been deprecated since May 2019.

remove deprecated functions in the peer package

---

crypto/ecdsa.go
crypto/ecdsa_test.go
crypto/ed25519.go
crypto/ed25519_test.go
crypto/fixture_test.go
crypto/key.go
crypto/openssl_common.go
crypto/rsa_go.go
crypto/rsa_test.go
crypto/secp256k1.go
crypto/secp256k1_test.go
peer/peer.go
peer/peer_test.go

This method has been deprecated since May 2019.

remove deprecated Bytes method from the Key interface

---

crypto/key.go
crypto/key_test.go

This was needed for secio. It has been deprecated for almost 2 years now. Let's get rid of it!

remove deprecated key stretching struct / function

---

peerstore/peerstore.go

There's really no reason to expire these after 10 minutes as opposed to 30. Given that our default DHT refresh interval is 10 minutes, setting this to 30 reduces the chances that we'll "forget" peers.

feat: keep addresses for longer

---

sec/insecure/insecure.go
sec/insecure/insecure_test.go
sec/security.go

The peer ID may be empty. This will be the common case. In that case, connections from any peer are accepted.
See https://github.com/libp2p/go-libp2p-transport-upgrader/pull/82#discussion_r702406483.

pass the peer ID to SecureInbound in the SecureTransport and SecureMuxer

---

.github/workflows/go-compat.yml

`gocompat` currently fails the build when an incompatible API change was made. This is annoying. It's would be a lot more helpful if it would just the author (and the reviewers) what's going on, so they can make an informed decision.
Example:
Related: https://github.com/protocol/.github/issues/188

make Go compat post a comment on the PR

---

network/network.go

Is there a special purpose to define two `io.Closer` in the `Network` interface?

remove duplicate io.Closer on Network interface

---

transport/transport.go

The timeout should be a configuration option for the swarm, not a global variable.
Related change in the swarm: https://github.com/libp2p/go-libp2p-swarm/pull/302.
We should probably do the same for the `AcceptTimeout`.

remove the DialTimeout

---

transport/transport.go

Related: https://github.com/libp2p/go-libp2p-transport-upgrader/pull/97.
Confirmed by building go-ipfs that this doesn't break anything in our stack.

remove the transport.AcceptTimeout

---

mux/mux.go
network/conn.go
network/errors.go
network/mux.go
network/network.go
network/rcmgr.go
network/stream.go
transport/transport.go

See https://github.com/libp2p/go-libp2p/issues/1260 for the proposal/design discussion.

Network Resource Manager interface

---

peer/peer.go

- Initialize and preallocate the slice of strings
- use the method `String` for each `ID` and put in the slice 
- return a string of ids separated by `, `
Tiny demonstration: https://go.dev/play/p/kd_nd-edWnr
Original suggestion -> https://github.com/ChainSafe/gossamer/pull/2267#discussion_r826306828

chore: add `String()` method to `IDSlice` type

---

crypto/ecdsa.go
crypto/ed25519.go
crypto/key_openssl.go
crypto/rsa_go.go
crypto/secp256k1.go
internal/catch/catch.go
internal/catch/catch_test.go
peer/addrinfo_serde.go
peer/record.go
record/envelope.go
record/record.go

Part of https://github.com/libp2p/go-libp2p/issues/1389
These kinds of functions:
1. Handle user input.
2. Often have out-of-bounds, null pointer, etc bugs.
3. Have completely isolated logic where local panics are unlikely to cause memory corruption elsewhere.

feat: harden encoding/decoding functions against panics

---

protocol/switch.go

As discussed in https://github.com/multiformats/go-multistream/pull/85, `NegotiateLazy` was pretty uninteresting: all that it did was do the writes asynchronously.
Thanks to @MarcoPolo for pointing out that we also need to deprecate the function on the interface in https://github.com/libp2p/go-libp2p/pull/1417#issuecomment-1106432555.

deprecate Negotiator.NegotiateLazy

---

network/notifee.go
network/notifee_test.go

As far as I can tell, nobody is using the `OpenedStream` and `ClosedStream` notification.
This is because they're not really useful: You can get a notification that the swarm opened a new stream, but you can read, write, close or reset the stream without interfering with the application. Therefore you won't even know which libp2p protocol is being negotiated on that stream.

remove OpenedStream and ClosedStream from Notifiee interface

---

canonicallog/canonicallog.go
canonicallog/canonicallog_test.go

These logs would normally be noisy, so we sample them. And randomly log 1 in N (N is configurable).
This means that most logs are pretty random, but patterns will emerge when there are a large number of similar events.
These logs can then be hooked up to fail2ban to automatically block abnormal peers for a bit.
Example:
A node starts a connection, sends a ping, and closes it. 100 times a second.
We log a connection established at a rate of 1 in 100 (1%).
This would log roughly once a second.
a fail2ban filter can ban a peer after 30 of these logs in a minute. (average of 50 conns/peer/second). And ban that peer for 60 minutes (not sure yet on the timing, but likely anything >10 min is good).
This solution can be applied to similar problems too. Basically anything that boils down to "this …

Add canonical peer status logging with sampling

---

network/rcmgr.go

Adds the endpoint parameter to OpenConnection method to resource manager. This enables an allowlist check that can use separate limits.

Add endpoint parameter to the OpenConnection method for ResourceManager

---

peer/peer.go
peer/peer_test.go

1. It's an alias for peer.ID.String
2. fmt.Stringer is the idiomatic way to get a string representation in Go.

deprecate peer.ID.Pretty

---

peer/peer.go
peer/peer_test.go
routing/query_serde.go

Trying to reduce the function sprawl in this package a bit.

deprecate peer.Encode in favor of peer.ID.String

---

peer/peer.go

This method is almost always used incorrectly. Contrary to what the name indicates, the following *does not* work:
```go
var id peer.ID
id2 := peer.IDFromString()
// id is not == id2 now!
```
The reason is that `String()` encodes the peer ID, so you need to call `Decode` instead. The existence of this function has cost me hours and hours of debugging, and we continue to use it in places where we shouldn't. We'd be better off if this function didn't exist.
Here's where we got this wrong in go-libp2p: https://github.com/libp2p/go-libp2p/pull/1644
And I'm pretty sure that lotus also got it wrong here: https://github.com/filecoin-project/lotus/blob/1de56d5e470d743e8b1542c889411360c84db431/node/modules/lp2p/libp2p.go#L70-L78 (I haven't followed the entire code path where these peer IDs …

remove peer.IDFromString

---

go.mod
go.sum
metrics/bandwidth_test.go

use a mock clock in bandwidth tests
